const tiles: ITile = {
  ground :{
    id: 0,
    animated: false,
    sprite: 'grass',
    frames: 0,
    physics: false,
    explosivable: false,
    isPlayer: false,
    isEnemy: false,
  },
  player: {
    id: 1,
    animated: false,
    sprite: 'player',
    frames: 0,
    physics: false,
    explosivable: false,
    isPlayer: true,
    isEnemy: false,
  },
  wall: {
    id: 2,
    animated: false,
    sprite: 'wall',
    frames: 0,
    physics: true,
    explosivable: false,
    isPlayer: false,
    isEnemy: false,
  },
  box: {
    id: 3,
    animated: true,
    sprite: 'box',
    frames: 6,
    physics: true,
    explosivable: true,
    isPlayer: false,
    isEnemy: false,
  },
  bomb: {
    id: 4,
    animated: true,
    sprite: 'bomb',
    frames: 3,
    physics: true,
    explosivable: false,
    isPlayer: false,
    isEnemy: false,
  },
  explosion: {
    id: 5,
    animated: true,
    sprite: 'explosion',
    frames: 5,
    physics: false,
    explosivable: false,
    isPlayer: false,
    isEnemy: false,
  },
  enemySimpleMove: {
    id: 6,
    animated: false,
    sprite: 'enemy',
    frames: 0,
    physics: false,
    explosivable: false,
    isPlayer: false,
    isEnemy: true,
  },
  enemyNestedMove: {
    id: 7,
    animated: false,
    sprite: 'enemy',
    frames: 0,
    physics: false,
    explosivable: false,
    isPlayer: false,
    isEnemy: true
  }
}

export default tiles