const tilesConfig: ITileConfig = {
  tileSize: 48,
  tiles: {
    ground :{
      id: 0,
      name: 'ground',
      color: 'black',
      size: 48,
      physics: false,
      explosivable: false,
      isPlayer: false,
      isEnemy: false,
    },
    player: {
      id: 1,
      name: 'player',
      color: 'blue',
      size: 30,
      physics: false,
      explosivable: false,
      isPlayer: true,
      isEnemy: false,
    },
    wall: {
      id: 2,
      name: 'wall',
      color: 'purple',
      size: 48,
      physics: true,
      explosivable: false,
      isPlayer: false,
      isEnemy: false,
    },
    box: {
      id: 3,
      name: 'box',
      color: 'grey',
      size: 36,
      physics: true,
      explosivable: true,
      isPlayer: false,
      isEnemy: false,
    },
    bomb: {
      id: 4,
      name: 'bomb',
      color: 'yellow',
      size: 40,
      physics: true,
      explosivable: false,
      isPlayer: false,
      isEnemy: false,
    },
    explosion: {
      id: 5,
      name: 'explosion',
      color: 'orange',
      size: 40,
      physics: false,
      explosivable: false,
      isPlayer: false,
      isEnemy: false,
    },
    enemySimpleMove: {
      id: 6,
      name: 'enemy-simple-move',
      color: 'red',
      size: 40,
      physics: false,
      explosivable: false,
      isPlayer: false,
      isEnemy: true,
    },
    enemyNestedMove: {
      id: 7,
      name: 'enemy-nested-move',
      color: 'Teal',
      size: 40,
      physics: false,
      explosivable: false,
      isPlayer: false,
      isEnemy: true
    }
  }
}

export default tilesConfig